// Ravintola Alexander
GET https://abo-academi.ravintolapalvelut.iss.fi/abo-academi

###

// Cotton Club
GET https://www.lounaat.info/lounas/cotton-club/vaasa

### 

// Mathilda & Café Oskar
GET https://www.lounaat.info/lounas/food-co-mathilda-cafe-oskar/vaasa

### 

// Ravintola August
GET https://www.lounaat.info/lounas/august-restaurant/vaasa